## -----------------------------------------------
## Basic Configuration
## -----------------------------------------------

title = "La revolución en el cuerpo"
copyright = "{year}"

## -----------------------------------------------
## Publish
## -----------------------------------------------

relativeURLs = "true"
#canonifyURLs = "true"

# Local
baseURL = "/"
publishDir = "public"

# Remote
#baseURL = "https://caressofsteel.github.io/demos/hugo/hugo-story/"
#publishDir = "//centos/sites/hugodev/hugostory/"

## -----------------------------------------------
## Hugo Built-in Features
## -----------------------------------------------

disableKinds = ["taxonomy", "section"]
# googleAnalytics = "G-XXXXXXXXXX"

## -----------------------------------------------
## Site Parameters
## -----------------------------------------------

[Params]
  description = "La revolución en el cuerpo: Historia ilustrada de la vestimenta en Buenos Aires de 1810 a 1850, por Rosario Oliva"
  logo = "images/banner.jpg"
  favicon = true

[Params.social]
  github = "https://github.com/"
  twitter = "https://twitter.com/chezrosario"
  email = "chezrosario@gmail.com"
  instagram = "https://www.instagram.com/rosarioolivailustradora/"
  linkedin = "https://www.linkedin.com/in/rosario-oliva-599aab1a/"
  behance = "https://www.behance.net/rosarioliva"
  telegram = "https://telegram.org"

[Params.asset]
  fontawesome_css = ["css/fontawesome-all.min.css"]
  fontawesome_js = ["js/fontawesome-all.min.js"]
